
package org.universAAL.ontology.c4a;

import org.universAAL.middleware.owl.IntRestriction;
import org.universAAL.middleware.owl.FloatRestriction;
import org.universAAL.middleware.owl.DoubleRestriction;
import org.universAAL.middleware.owl.LongRestriction;
import org.universAAL.middleware.owl.DataRepOntology;
import org.universAAL.middleware.owl.ManagedIndividual;
import org.universAAL.middleware.owl.MergedRestriction;
import org.universAAL.middleware.owl.OntClassInfoSetup;
import org.universAAL.middleware.owl.Ontology;
import org.universAAL.middleware.rdf.TypeMapper;
import org.universAAL.middleware.service.owl.ServiceBusOntology;
import org.universAAL.ontology.location.LocationOntology;
import org.universAAL.ontology.phThing.PhThingOntology;
import org.universAAL.ontology.shape.ShapeOntology;
import org.universAAL.ontology.space.SpaceOntology;

import javax.xml.datatype.XMLGregorianCalendar;
import org.universAAL.middleware.owl.ManagedIndividual;
import org.universAAL.middleware.service.owl.Service;
import org.universAAL.middleware.rdf.Resource;


//import the factory for this ontology
import org.universAAL.ontology.C4aFactory;


/**
 * This class provides the main representation of the c4a ontology 
 * for the universAAL platform.
 *
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public final class C4aOntology extends Ontology {

  private static C4aFactory factory = new C4aFactory();
  public static final String NAMESPACE ="http://ontology.universAAL.org/C4A#";
	
  public C4aOntology() {
    super(NAMESPACE);
  }

  public void create() {
    Resource r = getInfo();
    r.setResourceComment("");
    r.setResourceLabel("c4a");
    addImport(DataRepOntology.NAMESPACE);
    addImport(ServiceBusOntology.NAMESPACE);
    addImport(LocationOntology.NAMESPACE);
    addImport(PhThingOntology.NAMESPACE);
    addImport(ShapeOntology.NAMESPACE);
    addImport(SpaceOntology.NAMESPACE);
    // TODO: Add any additionally imported ontologies here
    

    // ******* Declaration of enumeration classes of the ontology ******* //
    OntClassInfoSetup oci_LEA_phase = createNewAbstractOntClassInfo(LEA_phase.MY_URI);

    // ******* Declaration of regular classes of the ontology ******* //
    OntClassInfoSetup oci_Walking_stop = createNewOntClassInfo(Walking_stop.MY_URI, factory, 0);
    OntClassInfoSetup oci_Enter_home = createNewOntClassInfo(Enter_home.MY_URI, factory, 1);
    OntClassInfoSetup oci_Exit_home = createNewOntClassInfo(Exit_home.MY_URI, factory, 2);
    OntClassInfoSetup oci_Stay_stop = createNewOntClassInfo(Stay_stop.MY_URI, factory, 3);
    OntClassInfoSetup oci_IndoorHomeMonitoring = createNewOntClassInfo(IndoorHomeMonitoring.MY_URI, factory, 4);
    OntClassInfoSetup oci_Stay = createNewOntClassInfo(Stay.MY_URI, factory, 5);
    OntClassInfoSetup oci_Stay_start = createNewOntClassInfo(Stay_start.MY_URI, factory, 6);
    OntClassInfoSetup oci_LEA = createNewOntClassInfo(LEA.MY_URI, factory, 7);
    OntClassInfoSetup oci_Walking_info = createNewOntClassInfo(Walking_info.MY_URI, factory, 8);
    OntClassInfoSetup oci_Walking = createNewOntClassInfo(Walking.MY_URI, factory, 9);
    OntClassInfoSetup oci_Exit_Bus = createNewOntClassInfo(Exit_Bus.MY_URI, factory, 10);
    OntClassInfoSetup oci_Walking_start = createNewOntClassInfo(Walking_start.MY_URI, factory, 11);
    OntClassInfoSetup oci_BodyState = createNewOntClassInfo(BodyState.MY_URI, factory, 12);
    OntClassInfoSetup oci_InterventionWithTransportation = createNewOntClassInfo(InterventionWithTransportation.MY_URI, factory, 13);
    OntClassInfoSetup oci_Enter_Bus = createNewOntClassInfo(Enter_Bus.MY_URI, factory, 14);

    // ******* Add content to enumeration classes of the ontology ******* //

    oci_LEA_phase.setResourceComment("");
    oci_LEA_phase.setResourceLabel("LEA_phase");
    oci_LEA_phase.toEnumeration(new ManagedIndividual[] {
       LEA_phase.start, LEA_phase.stop, LEA_phase.info });


    // ******* Add content to regular classes of the ontology ******* //
    oci_Walking_stop.setResourceComment("");
    oci_Walking_stop.setResourceLabel("Walking_stop");
    oci_Walking_stop.addSuperClass(Walking.MY_URI); 
    oci_Walking_stop.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.stop));
    
    oci_Enter_home.setResourceComment("");
    oci_Enter_home.setResourceLabel("Enter_home");
    oci_Enter_home.addSuperClass(IndoorHomeMonitoring.MY_URI);
    oci_Enter_home.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.start));

    oci_Exit_home.setResourceComment("");
    oci_Exit_home.setResourceLabel("Exit_home");
    oci_Exit_home.addSuperClass(IndoorHomeMonitoring.MY_URI); 
    oci_Exit_home.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.stop));

    oci_Stay_stop.setResourceComment("");
    oci_Stay_stop.setResourceLabel("Stay_stop");
    oci_Stay_stop.addSuperClass(Stay.MY_URI); 
    oci_Stay_stop.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.stop));

    oci_IndoorHomeMonitoring.setResourceComment("");
    oci_IndoorHomeMonitoring.setResourceLabel("IndoorHomeMonitoring");
    oci_IndoorHomeMonitoring.addSuperClass(LEA.MY_URI); 

    oci_Stay.setResourceComment("");
    oci_Stay.setResourceLabel("Stay");
    oci_Stay.addSuperClass(BodyState.MY_URI); 

    oci_Stay_start.setResourceComment("");
    oci_Stay_start.setResourceLabel("Stay_start");
    oci_Stay_start.addSuperClass(Stay.MY_URI); 
    oci_Stay_start.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.start));

    oci_LEA.setResourceComment("");
    oci_LEA.setResourceLabel("LEA");
    oci_LEA.addSuperClass(Service.MY_URI); 
    oci_LEA.addObjectProperty(LEA.PROP_L_E_A_PHASE).setFunctional();
    oci_LEA.addRestriction(MergedRestriction
      .getAllValuesRestrictionWithCardinality(LEA.PROP_L_E_A_PHASE, 
          LEA_phase.MY_URI, 1, 1));
    oci_LEA.addDatatypeProperty(LEA.PROP_TIMESTAMP).setFunctional();
    oci_LEA.addRestriction(MergedRestriction
      .getAllValuesRestrictionWithCardinality(LEA.PROP_TIMESTAMP, 
          TypeMapper.getDatatypeURI(XMLGregorianCalendar.class), 1, 1));

    oci_Walking_info.setResourceComment("");
    oci_Walking_info.setResourceLabel("Walking_info");
    oci_Walking_info.addSuperClass(Walking.MY_URI); 
    oci_Walking_info.addDatatypeProperty(Walking_info.PROP_POSITION_LONG).setFunctional();
    // @pabrilgimenez: is position_long the total distance wakled? why is it a Long? what units does it have?
    oci_Walking_info.addRestriction(MergedRestriction
      .getAllValuesRestrictionWithCardinality(Walking_info.PROP_POSITION_LONG, 
          TypeMapper.getDatatypeURI(Long.class), 1, 1));
    // @pabrilgimenez: is position_alt the altitude difference wakled? why is it a Long? what units does it have?
    oci_Walking_info.addDatatypeProperty(Walking_info.PROP_POSITION_ALT).setFunctional();
    oci_Walking_info.addRestriction(MergedRestriction
      .getAllValuesRestrictionWithCardinality(Walking_info.PROP_POSITION_ALT, 
          TypeMapper.getDatatypeURI(Long.class), 1, 1));
    // @pabrilgimenez: are long and alt reffering to longitude and latitude, as in GPS coordenates? are these both cumulative?
    // because I would recommend to use Location (as a Point instance) https://github.com/universAAL/ontology/wiki/Physical-World
    // maybe it would be interesting to have these properties as part of the walking class.
    oci_Walking_info.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.info));

    oci_Walking.setResourceComment("");
    oci_Walking.setResourceLabel("Walking");
    oci_Walking.addSuperClass(BodyState.MY_URI); 

    oci_Exit_Bus.setResourceComment("");
    oci_Exit_Bus.setResourceLabel("Exit_Bus");
    oci_Exit_Bus.addSuperClass(InterventionWithTransportation.MY_URI); 
    oci_Exit_Bus.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.stop));

    oci_Walking_start.setResourceComment("");
    oci_Walking_start.setResourceLabel("Walking_start");
    oci_Walking_start.addSuperClass(Walking.MY_URI); 
    oci_Walking_start.addRestriction(MergedRestriction.getFixedValueRestriction(LEA.PROP_L_E_A_PHASE, LEA_phase.start));

    oci_BodyState.setResourceComment("");
    oci_BodyState.setResourceLabel("BodyState");
    oci_BodyState.addSuperClass(LEA.MY_URI); 

    oci_InterventionWithTransportation.setResourceComment("");
    oci_InterventionWithTransportation.setResourceLabel("InterventionWithTransportation");
    oci_InterventionWithTransportation.addSuperClass(LEA.MY_URI); 

    oci_Enter_Bus.setResourceComment("");
    oci_Enter_Bus.setResourceLabel("Enter_Bus");
    oci_Enter_Bus.addSuperClass(InterventionWithTransportation.MY_URI); 

  }
}
