package org.universAAL.ontology.c4a;



/**
 * Ontological representation of Walking_info in the c4a ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public class Walking_info extends Walking {
  public static final String MY_URI = C4aOntology.NAMESPACE
    + "Walking_info";
  public static final String PROP_POSITION_LONG = C4aOntology.NAMESPACE
    + "position_long";
  public static final String PROP_POSITION_ALT = C4aOntology.NAMESPACE
    + "position_alt";


  public Walking_info () {
    super();
  }
  
  public Walking_info (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {
    if (PROP_POSITION_LONG.equals(propURI))
      return PROP_SERIALIZATION_FULL;
    if (PROP_POSITION_ALT.equals(propURI))
      return PROP_SERIALIZATION_FULL;
    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed() 
      && hasProperty(PROP_POSITION_LONG)
      && hasProperty(PROP_POSITION_ALT);
  }

  public long getPosition_long() {
	Long l = (Long) getProperty(PROP_POSITION_LONG);
	return (l == null) ? 0 : l.longValue();
  }		

  public void setPosition_long(long newPropValue) {
      changeProperty(PROP_POSITION_LONG, new Long(newPropValue));
  }		

  public long getPosition_alt() {
	Long l = (Long) getProperty(PROP_POSITION_ALT);
	return (l == null) ? 0 : l.longValue();
  }		

  public void setPosition_alt(long newPropValue) {
      changeProperty(PROP_POSITION_ALT, new Long(newPropValue));
  }		

}
