package org.universAAL.ontology.c4a;

import org.universAAL.middleware.owl.ManagedIndividual;


/**
 * Ontological representation of Walking_start in the c4a ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public class Walking_start extends Walking {
  public static final String MY_URI = C4aOntology.NAMESPACE
    + "Walking_start";


  public Walking_start () {
    super();
  }
  
  public Walking_start (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {
    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed() ;
  }

}
